"""H-6: statistics of the F2b physical layers of each country against their sanity ranges (V-04).

Reads `outputs/<ISO3>/siting_layers/artifacts/*.tif` for the given countries and writes a Markdown report. Each layer is compared with
the range it has, in this order:

1. the range `config/audit.yaml` holds under `layers` (PVOUT: the product's own statistics);
2. the range derived from the country's geometry or from the ISO 2533 standard atmosphere (`siting_layers/sanity.py`): air density from
   the DEM elevation span, distances from the bounding-box diagonal (`audit.yaml` `derived_ranges`);
3. none: Weibull A and k have no range until OQ-053 gives a sourced one. They are reported with their definition bound only
   (positive), and no range is invented.

Usage (GEOFREA_DATA_DIR set):
    python scripts/f2b_sanity_report.py PRT BRA IND > docs/_audit/2026-10_f2b_sanity.md
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd
import rasterio
import yaml

from geofrea.core import paths as core_paths
from geofrea.siting_layers.sanity import CountryGeometry, country_geometry, derived_range

REPO = Path(__file__).resolve().parents[1]
HEIGHTS = (100, 150, 200)
# layer -> (description, unit, audit.yaml key of a configured range or None, derived kind or None, lower bound kind, upper bound or None)
LAYERS: dict[str, tuple[str, str, str | None, str | None, str, float | None]] = {
    "dist_grid_km": ("Distance to the grid", "km", None, "dist_grid_km", "ge0", None),
    "dist_road_km": ("Distance to the road network", "km", None, "dist_road_km", "ge0", None),
    "pvout_kwh_kwp_day": ("PVOUT", "kWh/kWp/day", "solar", None, "ge0", 24.0),
}
for h in HEIGHTS:
    LAYERS[f"weibull_a_{h}m"] = (f"Weibull scale A at {h} m", "m/s", None, None, "gt0", None)
    LAYERS[f"weibull_k_{h}m"] = (f"Weibull shape k at {h} m", "-", None, None, "gt0", None)
    LAYERS[f"air_density_{h}m"] = (
        f"Air density at {h} m",
        "kg/m3",
        None,
        "air_density",
        "gt0",
        None,
    )


def _configured(audit: dict, key: str | None) -> tuple[float, float] | None:
    if key is None:
        return None
    rng = audit.get("layers", {}).get(key, {}).get("sanity_range")
    return (float(rng[0]), float(rng[1])) if rng else None


def _values(path: Path) -> np.ndarray | None:
    if not path.is_file():
        return None
    with rasterio.open(path) as src:
        return src.read(1, masked=True).astype("float64").compressed()


def _range_for(audit, name, audit_key, derived_kind, geometry: CountryGeometry):
    configured = _configured(audit, audit_key)
    if configured is not None:
        return configured, "audit.yaml"
    if derived_kind is not None:
        height = (
            float(name.split("_")[-1].removesuffix("m")) if derived_kind == "air_density" else None
        )
        tolerance = (
            audit.get("derived_ranges", {}).get(derived_kind, {}).get("tolerance_rel") or 0.0
        )
        return derived_range(derived_kind, geometry, height, tolerance), "derived"
    return None, "none (OQ-053)" if name.startswith("weibull") else "none"


def _candidate_density(iso: str) -> tuple[float, float] | None:
    """Lowest air density at 100 m among the wind candidate cells and among the wind cells with any eligible area (F3, central)."""
    folder = core_paths.phase_dir(iso, "land_eligibility", "artifacts")
    cells_path, cand_path = (
        folder / "cells_wind__central.parquet",
        folder / "candidates_wind__central.parquet",
    )
    if not (cells_path.is_file() and cand_path.is_file()):
        return None
    cells = pd.read_parquet(cells_path, columns=["air_density_100m", "eligible_area_km2"])
    cand = pd.read_parquet(cand_path, columns=["air_density_100m"])
    with_eligible = cells[cells["eligible_area_km2"] > 0]["air_density_100m"]
    return float(cand["air_density_100m"].min()), float(with_eligible.min())


def main(countries: list[str]) -> None:
    audit = yaml.safe_load((REPO / "config" / "audit.yaml").read_text(encoding="utf-8"))
    out: list[str] = [
        "# F2b physical layers: statistics against their sanity ranges (H-6, V-04)",
        "",
        (
            "Generated by `scripts/f2b_sanity_report.py`. Range source: `audit.yaml` (PVOUT, from the product's own statistics), "
            "`derived` (air density from the ISO 2533 standard atmosphere and the elevation span of the country's 30 m DEM tiles, widened by the relative quality-control tolerance of `audit.yaml`, +-5%; distances from the "
            "country's bounding-box diagonal; `siting_layers/sanity.py`), or `none` (Weibull A and k, OQ-053). Definition bound = the "
            "bound that follows from what the quantity is (positive scale, shape and density; non-negative distance; PVOUT at most 24)."
        ),
        "",
    ]
    for iso in countries:
        folder = core_paths.phase_dir(iso, "siting_layers", "artifacts")
        elevation = (
            core_paths.phase_dir(iso, "grid_alignment", "artifacts")
            / f"{iso}_elevation_aligned.tif"
        )
        geometry = country_geometry(
            elevation,
            core_paths.fetched_raw("copernicus_dem30", iso),
            core_paths.interim(iso, "sanity") / "dem30_extremes.json",
        )
        out += [
            f"## {iso}",
            "",
            (
                f"Elevation of the country (aligned DEM widened by the 30 m tiles): {geometry.z_min_m:.0f} to {geometry.z_max_m:.0f} m; bounding box "
                f"{geometry.west:.2f}, {geometry.south:.2f}, {geometry.east:.2f}, {geometry.north:.2f}."
            ),
            "",
            "| Layer | Unit | Valid pixels | Min | P1 | Median | P99 | Max | Range | Range source | Pixels outside | Breaks definition bound |",
            "|---|---|---|---|---|---|---|---|---|---|---|---|",
        ]
        notes: list[str] = []
        for name, (desc, unit, audit_key, derived_kind, kind, upper) in LAYERS.items():
            v = _values(folder / f"{name}.tif")
            if v is None or v.size == 0:
                out.append(
                    f"| {desc} | {unit} | {'missing' if v is None else 0} | | | | | | | | | |"
                )
                continue
            rng, source = _range_for(audit, name, audit_key, derived_kind, geometry)
            outside = "n/a" if rng is None else int(((v < rng[0]) | (v > rng[1])).sum())
            broken = int((v <= 0).sum()) if kind == "gt0" else int((v < 0).sum())
            if upper is not None:
                broken += int((v > upper).sum())
            q = np.percentile(v, [1, 50, 99])
            rng_text = "none" if rng is None else f"[{rng[0]:.4g}, {rng[1]:.4g}]"
            out.append(
                f"| {desc} | {unit} | {v.size:,} | {v.min():.4g} | {q[0]:.4g} | {q[1]:.4g} | {q[2]:.4g} | {v.max():.4g} | "
                f"{rng_text} | {source} | {outside} | {broken} |"
            )
            if name.startswith("weibull_k"):
                notes.append(
                    f"- {desc}: {100 * float((v < 1).mean()):.2f}% of the valid pixels have k < 1 (the density is then monotone "
                    "decreasing; read with the maps)."
                )
        density = _candidate_density(iso)
        if density is not None:
            notes.append(
                f"- Lowest air density at 100 m: {density[1]:.4g} kg/m3 among the wind cells that keep any eligible area, "
                f"{density[0]:.4g} kg/m3 among the wind candidate cells (F3, central scenario)."
            )
        out += ["", *notes, ""]
    print("\n".join(out))


if __name__ == "__main__":
    main(sys.argv[1:] or ["PRT", "BRA", "IND"])
