"""Run the V-01 scope (F1, F2a, exclusions E1-E3) on the synthetic ZZZ country and collect the rasters.

Shared by `scripts/freeze_v01_fixtures.py` (writes the frozen fixtures) and `test_v01_frozen.py` (compares
a fresh run against them), so both exercise exactly the same code path. ZZZ is deterministic and 600 pixels
wide, so the whole run takes seconds and the fixtures are a few hundred kB (V-01, METHODOLOGY section 5).

E1 protected and E2 water are the binary masks of `criteria_functions` (1 = free, 0 = excluded in that
function's convention); E3 riparian is frozen as the F2a river-distance raster it thresholds, because the
setback itself is a research parameter (OQ-002/003, H-3).
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

import numpy as np
import rasterio

from geofrea.core import paths as core_paths
from geofrea.core.config_loader import load_audit_config, load_parameters
from geofrea.core.geo_utils import load_mainland_boundary
from geofrea.suitability_criteria.criteria_functions import (
    compute_lakes_exclusion,
    compute_protected_areas,
)

REPO_ROOT = Path(__file__).resolve().parents[2]

def run_zzz(data_dir: Path) -> dict[str, np.ndarray]:
    """Generate the ZZZ fixture and run data_acquisition + grid_alignment under `data_dir`.

    Returns name -> array (float64). The fixture is regenerated by `scripts/generate_zzz_fixture.py` (it is
    deterministic), so the run needs nothing outside the repository.
    """
    import main  # repo-root script

    os.environ["GEOFREA_DATA_DIR"] = str(data_dir)
    subprocess.run(
        [sys.executable, str(REPO_ROOT / "scripts" / "generate_zzz_fixture.py")],
        check=True,
        env={**os.environ, "GEOFREA_DATA_DIR": str(data_dir)},
        capture_output=True,
    )
    settings = main.load_settings(main.SETTINGS_YAML)
    ok, _orchestrator, results = main.run_geofrea(
        "ZZZ",
        ["data_acquisition", "grid_alignment"],
        [],
        settings.geospatial.resolutions,
        settings.geospatial.distance_cap_km,
        load_audit_config(main.AUDIT_YAML),
        "v01-freeze",
        False,
    )
    assert ok, {k: v.status for k, v in results.items()}

    out_dir = core_paths.phase_dir("ZZZ", "grid_alignment", "artifacts")
    arrays: dict[str, np.ndarray] = {}
    for tif in sorted(Path(out_dir).glob("*.tif")):
        with rasterio.open(tif) as src:
            arrays[f"f2a/{tif.stem}"] = src.read(1).astype(np.float64)
    lakes = next(Path(out_dir).glob("*lakes_aligned.tif"))
    arrays["e2_water"] = compute_lakes_exclusion(str(lakes))[0].astype(np.float64)

    with rasterio.open(lakes) as src:
        transform, width, height, crs = src.transform, src.width, src.height, str(src.crs)
    raw = data_dir / "fixtures" / "synthetic_zzz" / "raw"
    mainland = load_mainland_boundary(next((raw / "countries_borders").rglob("gadm41_ZZZ_0.shp")))
    wdpa = next((raw / "protected_areas").glob("*.gpkg"))
    strict = load_parameters(main.PARAMETERS_JSON).criteria.iucn_strict_categories.value
    protected = compute_protected_areas(wdpa, mainland, transform, width, height, crs, strict)[0]
    arrays["e1_protected"] = protected.astype(np.float64)
    return arrays
